// src/components/Contact.jsx
import "../styles/contact.css";

export default function Contact({ language }) {
  const translations = {
    en: {
      heading: "Contact Me",
      phoneLabel: "Phone",
      linkedinLabel: "LinkedIn Profile",
      githubLabel: "GitHub Profile",
    },
    "pt-BR": {
      heading: "Contato",
      phoneLabel: "Telefone",
      linkedinLabel: "Perfil no LinkedIn",
      githubLabel: "Perfil no GitHub",
    },
  };

  const { heading, phoneLabel, linkedinLabel, githubLabel } =
    translations[language];
  return (
    <>
      <section id="contact">
        <h2>{heading}</h2>
        <ul>
          <li>Email: caiohenrique29@protonmail.com</li>
          <li>{phoneLabel}: +51 21 99350-2805</li>
          <li>
            <a href="https://www.linkedin.com/in/caio-henrique-c7351/">
              <i className="fa fa-external-link" aria-hidden="true"></i>
              {linkedinLabel}
            </a>
          </li>
          <li>
            <a href="https://github.com/caiohenrique-3">
              <i className="fa fa-external-link" aria-hidden="true"></i>
              {githubLabel}
            </a>
          </li>
        </ul>
      </section>
    </>
  );
}

// src/lib/Contact.svelte
<section id="contato" class="text-white p-6 max-w-4xl mx-auto">
  <h1 class="text-3xl pb-3 text-emerald-300">Contato</h1>
  <ul>
    <li class="pb-3">caiohenrique29@protonmail.com</li>
    <li class="pb-3">(21) 99350-2805</li>
    <li class="pb-3">
      <a
        href="https://www.linkedin.com/in/caio-henrique-c7351/"
        class="underline underline-offset-4 hover:text-emerald-300"
      >
        <i class="fa fa-external-link" aria-hidden="true" />
        Perfil no LinkedIn
      </a>
    </li>
    <li class="pb-3">
      <a
        href="https://github.com/caiohenrique-3"
        class="underline underline-offset-4 hover:text-emerald-300"
      >
        <i class="fa fa-external-link" aria-hidden="true" />
        Perfil no GitHub
      </a>
    </li>
  </ul>
</section>
