// src/components/Projects.jsx
import { useState } from "react";
import projectsData from "../data/projectsData";
import "../styles/projects.css";

export default function Projects(props) {
  const project = props.project;
  const { language } = props;

  const {
    title,
    description,
    technologies,
    imgAlt,
    showImageLabel,
    hideImageLabel,
    demoLabel,
    sourceCodeLabel,
  } = projectsData.find((p) => p.id === project.id);

  const [showImage, setShowImage] = useState(false);

  const handleClick = () => {
    setShowImage(!showImage);
  };

  return (
    <>
      <div className="project">
        <h3>{title[language]}</h3>
        <p>{description[language]} {technologies[language]}</p>
        <div className="img-container">
          {showImage && (
            <img src={project.img} alt={imgAlt[language]} loading="lazy" />
          )}
        </div>
        <ul>
          <li>
            <button onClick={handleClick}>
              <i
                className={`fa ${showImage ? "fa-eye-slash" : "fa-eye"}`}
                aria-hidden="true"
              >
              </i>
              {showImage ? hideImageLabel[language] : showImageLabel[language]}
            </button>
          </li>
          <li>
            <a href={project.demo}>
              <i className="fa fa-external-link" aria-hidden="true"></i>
              {demoLabel[language]}
            </a>
          </li>
          <li>
            <a href={project.sourceCode}>
              <i className="fa fa-github-alt" aria-hidden="true"></i>
              {sourceCodeLabel[language]}
            </a>
          </li>
        </ul>
      </div>
    </>
  );
}

// src/lib/Projects.svelte
<script>
  // dependencies
  import { onMount } from "svelte";
  import { register } from "swiper/element/bundle";

  register();

  // data
  import projects from "../data/projects";

  // Show/hide project showcase
  let showImage = {};

  onMount(() => {
    projects.forEach((project) => {
      showImage[project.id] = false;
    });
  });

  function handleClick(id) {
    showImage[id] = !showImage[id];
  }

  // Display projects based on category
  let currentCategory = "All";

  // Counting number of projects in category
  function countProjects(category) {
    if (category === "All") {
      return projects.length;
    } else {
      return projects.filter((project) =>
        project.technologies.includes(category)
      ).length;
    }
  }
</script>

<main id="projetos" class="text-white p-6 max-w-4xl mx-auto">
  <div class="flex pb-6">
    <h2 class="text-3xl text-emerald-300 pb-3 pr-3">Projetos</h2>

    <select bind:value={currentCategory} class="text-black pl-3 h-10">
      <option value="All">All ({countProjects("All")})</option>
      <option value="JavaScript"
        >JavaScript ({countProjects("JavaScript")})</option
      >
      <option value="React">React ({countProjects("React")})</option>
      <option value="Java">Java ({countProjects("Java")})</option>
      <option value="Python">Python ({countProjects("Python")})</option>
    </select>
  </div>

  <swiper-container loop="true" slides-per-view="1">
    {#each projects.filter((project) => currentCategory === "All" || project.technologies.includes(currentCategory)) as project (project.id)}
      <swiper-slide key={project.id}>
        <div class="project">
          <h3>{project.title}</h3>
          <p>{project.description} {project.technologies}</p>
          <div class="img-container">
            {#if showImage[project.id]}
              <img src={project.img} alt="Showcase" loading="lazy" />
            {/if}
          </div>
          <ul>
            <li>
              <button on:click={() => handleClick(project.id)}>
                <i
                  class={`fa ${
                    showImage[project.id] ? "fa-eye-slash" : "fa-eye"
                  }`}
                  aria-hidden="true"
                />
                {showImage[project.id]
                  ? "Clique para ocultar a imagem"
                  : "Clique para exibir a imagem"}
              </button>
            </li>
            <li>
              <a href={project.demo}>
                <i class="fa fa-external-link" aria-hidden="true" />
                Demonstração
              </a>
            </li>
            <li>
              <a href={project.sourceCode}>
                <i class="fa fa-github-alt" aria-hidden="true" />
                Código fonte
              </a>
            </li>
          </ul>
        </div>
      </swiper-slide>
    {/each}
  </swiper-container>
</main>
